// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEBvDgYQql_GOM5mMq1ssNSlWKcHiTYSM',
    appId: '1:1061228693144:web:679a6013218fcaa61d72ed',
    messagingSenderId: '1061228693144',
    projectId: 'dmessages-1fd4b',
    authDomain: 'dmessages-1fd4b.firebaseapp.com',
    storageBucket: 'dmessages-1fd4b.firebasestorage.app',
    measurementId: 'G-DB9W5W2JJH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxvJ3AuhWLQIh79EvMAwe0zr231KCDXZw',
    appId: '1:1061228693144:android:c6d22b80a54d45a01d72ed',
    messagingSenderId: '1061228693144',
    projectId: 'dmessages-1fd4b',
    storageBucket: 'dmessages-1fd4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCStUR_d1W6yOT_xHyyflIpNC0PURVQgJc',
    appId: '1:1061228693144:ios:5e60a92a43fa51371d72ed',
    messagingSenderId: '1061228693144',
    projectId: 'dmessages-1fd4b',
    storageBucket: 'dmessages-1fd4b.firebasestorage.app',
    iosBundleId: 'com.example.dmessages',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCStUR_d1W6yOT_xHyyflIpNC0PURVQgJc',
    appId: '1:1061228693144:ios:5e60a92a43fa51371d72ed',
    messagingSenderId: '1061228693144',
    projectId: 'dmessages-1fd4b',
    storageBucket: 'dmessages-1fd4b.firebasestorage.app',
    iosBundleId: 'com.example.dmessages',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEBvDgYQql_GOM5mMq1ssNSlWKcHiTYSM',
    appId: '1:1061228693144:web:f348aafa593dba161d72ed',
    messagingSenderId: '1061228693144',
    projectId: 'dmessages-1fd4b',
    authDomain: 'dmessages-1fd4b.firebaseapp.com',
    storageBucket: 'dmessages-1fd4b.firebasestorage.app',
    measurementId: 'G-ZT372FBNP2',
  );
}
